# Generated by Django 5.1.7 on 2025-03-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phoneNumbers',
            fields=[
                ('phoneNumer', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('passportSeries', models.CharField(max_length=4)),
                ('passportNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minutes', models.IntegerField()),
                ('sms', models.IntegerField()),
                ('internet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivateServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idServices', models.IntegerField()),
                ('activationDate', models.DateTimeField()),
                ('deactivationDate', models.DateTimeField()),
                ('phoneNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.phonenumbers')),
            ],
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='idSubscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.subscriberpersonaldata'),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='idTariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logIn.tariff'),
        ),
        migrations.CreateModel(
            name='TariffServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(to='logIn.services')),
                ('tariff', models.ManyToManyField(to='logIn.tariff')),
            ],
        ),
    ]
