# Generated by Django 5.1.7 on 2025-03-20 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateservices',
            name='idServices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.services'),
        ),
    ]
