# Generated by Django 5.1.7 on 2025-03-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0002_alter_activateservices_idservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='phoneNumer',
            new_name='phoneNumber',
        ),
    ]
