# Generated by Django 5.1.7 on 2025-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0003_rename_phonenumer_phonenumbers_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberpersonaldata',
            name='birthday',
            field=models.DateField(default='2000-05-14'),
            preserve_default=False,
        ),
    ]
