# Generated by Django 5.1.7 on 2025-03-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0004_subscriberpersonaldata_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberpersonaldata',
            name='birthday',
        ),
    ]
