# Generated by Django 5.1.7 on 2025-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0005_remove_subscriberpersonaldata_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberpersonaldata',
            name='birthday',
            field=models.DateField(default='2000-05-14'),
        ),
    ]
