# Generated by Django 5.1.7 on 2025-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0006_subscriberpersonaldata_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberpersonaldata',
            name='birthday',
            field=models.DateField(),
        ),
    ]
