# Generated by Django 5.1.7 on 2025-03-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0007_alter_subscriberpersonaldata_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffservices',
            name='services',
        ),
        migrations.RemoveField(
            model_name='tariffservices',
            name='tariff',
        ),
        migrations.AddField(
            model_name='tariffservices',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.services'),
        ),
        migrations.AddField(
            model_name='tariffservices',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.tariff'),
        ),
    ]
