# Generated by Django 5.1.7 on 2025-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0008_remove_tariffservices_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateservices',
            name='deactivationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
