# Generated by Django 5.1.7 on 2025-03-21 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0009_alter_activateservices_deactivationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phoneNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.phonenumbers')),
            ],
        ),
    ]
