# Generated by Django 5.1.7 on 2025-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0010_financehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phoneNumber',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
