# Generated by Django 5.1.7 on 2025-04-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0011_alter_phonenumbers_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('communicationMethod', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('phoneNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logIn.phonenumbers')),
            ],
        ),
    ]
