# Generated by Django 5.1.7 on 2025-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0012_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='date',
            new_name='dateEnd',
        ),
        migrations.AddField(
            model_name='application',
            name='dateStart',
            field=models.DateTimeField(default='2000-05-14'),
            preserve_default=False,
        ),
    ]
