# Generated by Django 5.1.7 on 2025-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0013_rename_date_application_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
