# Generated by Django 5.1.7 on 2025-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0015_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='id',
        ),
        migrations.AlterField(
            model_name='admins',
            name='login',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
