# Generated by Django 5.1.7 on 2025-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0016_remove_admins_id_alter_admins_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='login',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
